### ISSUE TITLE
Xaml compilation error: No property, bindable property, or event found for 'Text', or mismatch type between value and property

### ISSUE THREAD

**Issue by AlejandroPiCano** [SuavePirate/MaterialEntry#1]
Hello,

I'm using the MaterialEntry control like the example but using Binding in the property Text, for example:

<local:MaterialEntry
AccentColor = "Green"
PlaceHolder="Code"
Text={Binding SelectedUser.Code, Mode=TwoWay}
/>

and I get the error when compiling:
 No property, bindable property, or event found for 'Text', or mismatch type between value and property

However, using a simple Entry, like this works:
<Entry
PlaceHolder="Code"
Text={Binding SelectedUser.Code, Mode=TwoWay}
/>

How i use this control and use my own BindingContext?

Thanks!

**Comment by SuavePirate** [comment]
You're missing quotes... {Binding SelectedUser.code, Mode=TwoWay} should have quotes around it.

**Comment by AlejandroPiCano** [comment]
Sorry, I wrote it wrong here, as I have it is with comillas "", as you say, this is not the reason for the error. Can you help me please?

Thanks. 
Greetings

**Comment by SuavePirate** [comment]
I'm not seeing this error. Did you look at the demo in this repository?

**Comment by AlejandroPiCano** [comment]
Yes, I've seen it, but not used data binding in the demo.If i use the control without binding its works, however with a viewmodel associated the binding is not working.

**Comment by SuavePirate** [comment]
I mean, I use the library as is with many of my projects that are full MVVM with no problems. What does your set up look like? I can update the demo to use some data binding if that helps.

**Comment by AlejandroPiCano** [comment]
Yes, it would be very useful have an example using data binding. Thank you

**Comment by SuavePirate** [comment]
The example has been updated to demonstrate data binding.
