### ISSUE TITLE
Binding error: No property, bindable property, or event found for 'Text', or mismatch type between value and property

### ISSUE THREAD

**Issue by AlejandroPiCano** [SuavePirate/MaterialEntry#2]
Hello,

I'm using the MaterialEntry control like the example but using Binding in the property Text, for example:

<local:MaterialEntry
 AccentColor = "Green"
 PlaceHolder="Code"
 Text="{Binding SelectedUser.Code, Mode=TwoWay}"
 />

and I get the error when compiling:
 No property, bindable property, or event found for 'Text', or mismatch type between value and property

However, using a simple Entry, like this works:

How i use this control and use my own BindingContext?

Thanks!

**Comment by SuavePirate** [comment]
Closing this one and re-opened the first one.
